In [1]:
# Dependencies and Setup

import pandas as pd
import numpy as np

In [37]:
# read csv files
inspections_data_path = "Data/COUNTY_OF_LOS_ANGELES_RESTAURANT_AND_MARKET_VIOLATIONS.csv"
inspections_data = pd.read_csv(inspections_data_path)
inspections_data

,SERIAL NUMBER,VIOLATION STATUS,VIOLATION CODE,VIOLATION DESCRIPTION,POINTS
0,DA000211Z,OUT OF COMPLIANCE,F006,# 06. Adequate handwashing facilities supplied...,2.0
1,DA000211Z,OUT OF COMPLIANCE,F044,"# 44. Floors, walls and ceilings: properly bui...",1.0
2,DA000211Z,OUT OF COMPLIANCE,F014,# 14. Food contact surfaces: clean and sanitized,2.0
3,DA000211Z,OUT OF COMPLIANCE,F029,"# 29. Toxic substances properly identified, st...",1.0
4,DA000211Z,OUT OF COMPLIANCE,F035,# 35. Equipment/Utensils - approved; installed...,1.0
...,...,...,...,...,...
829453,DAZZZ6W6B,OUT OF COMPLIANCE,F044,"# 44. Floors, walls and ceilings: properly bui...",1.0
829454,DAZZZNXH1,OUT OF COMPLIANCE,F025,# 25. Personal cleanliness and hair restraints,1.0
829455,DAZZZNXH1,OUT OF COMPLIANCE,F052,# 01b. Food safety certification,2.0
829456,DAZZZNXH1,OUT OF COMPLIANCE,F036,"# 36. Equipment, utensils and linens: storage ...",1.0
829457,DAZZZNXH1,OUT OF COMPLIANCE,F035,# 35. Equipment/Utensils - approved; installed...,1.0

In [53]:
# create a new data frame that has only the serial number and violation code columns

reduced_data = pd.DataFrame(inspections_data)[["SERIAL NUMBER", "VIOLATION  STATUS", "VIOLATION CODE", "POINTS"]].reset_index().assign
reduced_data

       SERIAL NUMBER  VIOLATION  STATUS VIOLATION CODE  POINTS
0          DA000211Z  OUT OF COMPLIANCE           F006     2.0
1          DA000211Z  OUT OF COMPLIANCE           F044     1.0
2          DA000211Z  OUT OF COMPLIANCE           F014     2.0
3          DA000211Z  OUT OF COMPLIANCE           F029     1.0
4          DA000211Z  OUT OF COMPLIANCE           F035     1.0
...              ...                ...            ...     ...
829453     DAZZZ6W6B  OUT OF COMPLIANCE           F044     1.0
829454     DAZZZNXH1  OUT OF COMPLIANCE           F025     1.0
829455     DAZZZNXH1  OUT OF COMPLIANCE           F052     2.0
829456     DAZZZNXH1  OUT OF COMPLIANCE           F036     1.0
829457     DAZZZNXH1  OUT OF COMPLIANCE           F035     1.0

[829458 rows x 4 columns]

In [60]:
reduced_data.to_csv("Data/serial_number_and_violation_code_data.csv", index=False)

In [69]:
reduced_data.groupby(["SERIAL NUMBER", "VIOLATION  STATUS","VIOLATION CODE"]).count().sort_values(by="POINTS")

                                                POINTS
SERIAL NUMBER VIOLATION  STATUS VIOLATION CODE
DA000211Z     OUT OF COMPLIANCE F006                 1
DAPCB6ENE     OUT OF COMPLIANCE F014                 1
                                F030                 1
                                F033                 1
                                F042                 1
...                                                ...
DA89G8HEK     OUT OF COMPLIANCE F023                 2
                                F030                 2
DACZKRTVG     OUT OF COMPLIANCE F042                 2
DALJI3GRM     OUT OF COMPLIANCE F033                 2
DABUBEYCW     OUT OF COMPLIANCE F002                 3

[829439 rows x 1 columns]

In [52]:
# create a new data frame that has only the serial number and violation code columns

viocode_viodesc_df = inspections_data[["VIOLATION CODE", "VIOLATION DESCRIPTION"]].drop_duplicates()
viocode_viodesc_df

       VIOLATION CODE                              VIOLATION DESCRIPTION
0                F006  # 06. Adequate handwashing facilities supplied...
1                F044  # 44. Floors, walls and ceilings: properly bui...
2                F014   # 14. Food contact surfaces: clean and sanitized
3                F029  # 29. Toxic substances properly identified, st...
4                F035  # 35. Equipment/Utensils - approved; installed...
...               ...                                                ...
455646           W044  Garbage / Rubbish receptacles maintained clean...
457572           W053                                  Permit Suspension
559515           W004                                 Food storage space
651069           W050                              Food properly labeled
653360           CV15                    COVID-19 Higher Risk Businesses

[100 rows x 2 columns]

In [59]:
viocode_viodesc_df.to_csv("Data/ violation_code.csv", index=False)

In [57]:
viocode_viodesc_df.value_counts().sort_values()

VIOLATION CODE  VIOLATION DESCRIPTION
W053            Permit Suspension                                              1
W050            Food properly labeled                                          1
W048            Permits Available                                              1
W044            Garbage / Rubbish receptacles maintained clean and sanitary    1
W041            Premises maintained clean and sanitary                         1
                                                                              ..
CV03            COVID-19 Limit the number of people in the facility            1
F003            # 03. No discharge from eyes, nose, and mouth                  1
F004            # 04. Proper eating, drinking, or tobacco use                  1
CV15            COVID-19 Higher Risk Businesses                                1
CV01            COVID-19 Employee Face Cover Required                          1
Length: 100, dtype: int64

In [62]:
inspections_facilities_path = "Data/INSPECTIONS_facilities.csv"
facilities_data = pd.read_csv(inspections_facilities_path)
facilities_data

,ACTIVITY DATE,OWNER ID,OWNER NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,SERVICE CODE,SERVICE DESCRIPTION,SCORE,SERIAL NUMBER,EMPLOYEE ID,FACILITY ID
0,7/17/2018,OW0127203,"VALLEY WINGS., LLC",PR0151832,WINGSTOP,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,1,ROUTINE INSPECTION,96,DATYINYIO,EE0000683,FA0163608
1,7/18/2018,OW0028924,"PPR., INC.",PR0045023,SUBWAY #2234,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1,ROUTINE INSPECTION,95,DA02EPFLB,EE0001072,FA0049283
2,7/23/2018,OW0013042,GENERAL NUTRITION CORP,PR0157146,GNC,ACTIVE,1610,"FOOD MKT RETAIL (1-1,999 SF) LOW RISK",1,ROUTINE INSPECTION,96,DAZZWSP9J,EE0001093,FA0166817
3,7/23/2018,OW0034634,"SWH MIMI'S CAFE, LLC.",PR0006841,MIMI'S CAFE,ACTIVE,1641,RESTAURANT (151 + ) SEATS HIGH RISK,1,ROUTINE INSPECTION,91,DAKT8SUQJ,EE0000161,FA0040785
4,7/24/2018,OW0252823,TORIBIO HUERTA,PR0211662,HUERTA'S PRODUCE,INACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1,ROUTINE INSPECTION,95,DAJ70SZE8,EE0000997,FA0261147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187508,9/2/2020,OW0226925,"ORIGINAL BILL'S DRIVE IN, INC",PR0176997,ORIGINAL BILL'S DRIVE IN,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,1,ROUTINE INSPECTION,97,DAYJ6WA58,EE0000188,FA0222004
187509,10/20/2020,OW0012190,FORTUNE COMMERCIAL CORP.,PR0022232,SEAFOOD CITY SEAFOOD DEPT,ACTIVE,1612,"FOOD MKT RETAIL (1-1,999 SF) HIGH RISK",1,ROUTINE INSPECTION,94,DA4NDSPWZ,EE0000206,FA0070222
187510,10/20/2020,OW0031282,LA VAQUITA MINI MARKET,PR0027071,LA VAQUITA,ACTIVE,1612,"FOOD MKT RETAIL (1-1,999 SF) HIGH RISK",1,ROUTINE INSPECTION,92,DAZOZVZ6U,EE0000045,FA0021179
187511,9/16/2020,OW0185406,THE MODERN TEA ROOM LLC,PR0173610,THE MODERN TEA ROOM,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1,ROUTINE INSPECTION,96,DAI0YQAOM,EE0001085,FA0179927
187512,10/8/2020,OW0181391,"GRAB N GO JUICE, LLC",PR0218730,JAMBA JUICE #1591,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1,ROUTINE INSPECTION,96,DAAISJXCO,EE0000006,FA0267326

In [65]:
facilities_data["SERIAL NUMBER"].nunique()

187513